name: Setup Infrastructure
on:
  push:
    branches:
      - master
jobs:
  test-infra:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_name_tag_value: ${{ secrets.NAME_TAG_VALUE }}
      TF_VAR_owner_tag_value: ${{ secrets.OWNER_TAG_VALUE }}
      TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.7'
      - name: Install Modules
        working-directory: test
        run: |
          pwd
          go get -v -t -d .
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi
      - name: Test Infrastructure
        working-directory: test
        run: go test -v -timeout 30m
